### ISSUE TITLE
LICENSE.md is missing date and name of copyright holder

### ISSUE THREAD

**Issue by rahobbs** [TouchType/CornedBeef#22]
LICENSE.md contains the line `Copyright {yyyy} {name of copyright owner}`. Per http://www.apache.org/licenses/LICENSE-2.0, "To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!)"

**Comment by lachiemurray** [comment]
Thanks! Created https://github.com/TouchType/CornedBeef/pull/32

**Comment by lachiemurray** [comment]
Resolved by https://github.com/TouchType/CornedBeef/pull/32
